ALTER TABLE students
MODIFY COLUMN college_id BIGINT NOT NULL;

ALTER TABLE products
MODIFY COLUMN college_id BIGINT NOT NULL;

ALTER TABLE orders
MODIFY COLUMN college_id BIGINT NOT NULL;

ALTER TABLE notifications
MODIFY COLUMN college_id BIGINT NOT NULL;