spring.application.name=backend
spring.datasource.url=jdbc:mysql://localhost:3306/skip_q
spring.datasource.username=root
spring.datasource.password=11052006

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true